spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: r1
              uri: http://localhost:8088/
              predicates:
                - Path=/client/**,/clients/**
            - id: r2
              uri: http://localhost:8089/
              predicates:
                - Path=/voiture/**,/voitures/**